# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import msextractor_pb2 as msextractor__pb2


class MSExtractorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getDecomposition = channel.unary_unary(
                '/msextractor.MSExtractor/getDecomposition',
                request_serializer=msextractor__pb2.DecompRequest.SerializeToString,
                response_deserializer=msextractor__pb2.Decomposition.FromString,
                )


class MSExtractorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getDecomposition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MSExtractorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getDecomposition': grpc.unary_unary_rpc_method_handler(
                    servicer.getDecomposition,
                    request_deserializer=msextractor__pb2.DecompRequest.FromString,
                    response_serializer=msextractor__pb2.Decomposition.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'msextractor.MSExtractor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MSExtractor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getDecomposition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/msextractor.MSExtractor/getDecomposition',
            msextractor__pb2.DecompRequest.SerializeToString,
            msextractor__pb2.Decomposition.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
