# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msextractor/v2/msextractor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msextractor/v2/msextractor.proto',
  package='msextractor',
  syntax='proto3',
  serialized_options=b'\n\026com.decomp.msextractorB\020MSExtractorProtoP\001\242\002\003MSE',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n msextractor/v2/msextractor.proto\x12\x0bmsextractor\"\xcd\x01\n\rDecompRequest\x12\x0f\n\x07\x61ppName\x18\x01 \x01(\t\x12\x0f\n\x07\x61ppData\x18\x02 \x01(\t\x12:\n\x0fhyperParameters\x18\x03 \x01(\x0b\x32\x1c.msextractor.HyperParametersH\x00\x88\x01\x01\x12\x12\n\x05level\x18\x04 \x01(\tH\x01\x88\x01\x01\x12\x1a\n\risDistributed\x18\x05 \x01(\x08H\x02\x88\x01\x01\x42\x12\n\x10_hyperParametersB\x08\n\x06_levelB\x10\n\x0e_isDistributed\"\xff\x02\n\x0fHyperParameters\x12\x1e\n\x11\x44\x65\x63ompositionName\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x1d\n\x10numMicroservices\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x1b\n\x0enumGenerations\x18\x03 \x01(\x03H\x02\x88\x01\x01\x12\x1b\n\x0enumPopulations\x18\x04 \x01(\x03H\x03\x88\x01\x01\x12\x19\n\x0cmutationProb\x18\x05 \x01(\x02H\x04\x88\x01\x01\x12\x1a\n\rattributeProb\x18\x06 \x01(\x02H\x05\x88\x01\x01\x12\x1a\n\rcrossoverProb\x18\x07 \x01(\x02H\x06\x88\x01\x01\x12\x11\n\x04seed\x18\x08 \x01(\x03H\x07\x88\x01\x01\x42\x14\n\x12_DecompositionNameB\x13\n\x11_numMicroservicesB\x11\n\x0f_numGenerationsB\x11\n\x0f_numPopulationsB\x0f\n\r_mutationProbB\x10\n\x0e_attributeProbB\x10\n\x0e_crossoverProbB\x07\n\x05_seed\"*\n\tPartition\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63lasses\x18\x02 \x03(\t\"{\n\rDecomposition\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61ppName\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\r\n\x05level\x18\x04 \x01(\t\x12*\n\npartitions\x18\x05 \x03(\x0b\x32\x16.msextractor.Partition2[\n\x0bMSExtractor\x12L\n\x10getDecomposition\x12\x1a.msextractor.DecompRequest\x1a\x1a.msextractor.Decomposition\"\x00\x42\x32\n\x16\x63om.decomp.msextractorB\x10MSExtractorProtoP\x01\xa2\x02\x03MSEb\x06proto3'
)




_DECOMPREQUEST = _descriptor.Descriptor(
  name='DecompRequest',
  full_name='msextractor.DecompRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='appName', full_name='msextractor.DecompRequest.appName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='appData', full_name='msextractor.DecompRequest.appData', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hyperParameters', full_name='msextractor.DecompRequest.hyperParameters', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='level', full_name='msextractor.DecompRequest.level', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isDistributed', full_name='msextractor.DecompRequest.isDistributed', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_hyperParameters', full_name='msextractor.DecompRequest._hyperParameters',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_level', full_name='msextractor.DecompRequest._level',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_isDistributed', full_name='msextractor.DecompRequest._isDistributed',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=50,
  serialized_end=255,
)


_HYPERPARAMETERS = _descriptor.Descriptor(
  name='HyperParameters',
  full_name='msextractor.HyperParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='DecompositionName', full_name='msextractor.HyperParameters.DecompositionName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='numMicroservices', full_name='msextractor.HyperParameters.numMicroservices', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='numGenerations', full_name='msextractor.HyperParameters.numGenerations', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='numPopulations', full_name='msextractor.HyperParameters.numPopulations', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mutationProb', full_name='msextractor.HyperParameters.mutationProb', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attributeProb', full_name='msextractor.HyperParameters.attributeProb', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='crossoverProb', full_name='msextractor.HyperParameters.crossoverProb', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='seed', full_name='msextractor.HyperParameters.seed', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_DecompositionName', full_name='msextractor.HyperParameters._DecompositionName',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_numMicroservices', full_name='msextractor.HyperParameters._numMicroservices',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_numGenerations', full_name='msextractor.HyperParameters._numGenerations',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_numPopulations', full_name='msextractor.HyperParameters._numPopulations',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_mutationProb', full_name='msextractor.HyperParameters._mutationProb',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_attributeProb', full_name='msextractor.HyperParameters._attributeProb',
      index=5, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_crossoverProb', full_name='msextractor.HyperParameters._crossoverProb',
      index=6, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_seed', full_name='msextractor.HyperParameters._seed',
      index=7, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=258,
  serialized_end=641,
)


_PARTITION = _descriptor.Descriptor(
  name='Partition',
  full_name='msextractor.Partition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='msextractor.Partition.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='classes', full_name='msextractor.Partition.classes', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=643,
  serialized_end=685,
)


_DECOMPOSITION = _descriptor.Descriptor(
  name='Decomposition',
  full_name='msextractor.Decomposition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='msextractor.Decomposition.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='appName', full_name='msextractor.Decomposition.appName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='language', full_name='msextractor.Decomposition.language', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='level', full_name='msextractor.Decomposition.level', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='partitions', full_name='msextractor.Decomposition.partitions', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=687,
  serialized_end=810,
)

_DECOMPREQUEST.fields_by_name['hyperParameters'].message_type = _HYPERPARAMETERS
_DECOMPREQUEST.oneofs_by_name['_hyperParameters'].fields.append(
  _DECOMPREQUEST.fields_by_name['hyperParameters'])
_DECOMPREQUEST.fields_by_name['hyperParameters'].containing_oneof = _DECOMPREQUEST.oneofs_by_name['_hyperParameters']
_DECOMPREQUEST.oneofs_by_name['_level'].fields.append(
  _DECOMPREQUEST.fields_by_name['level'])
_DECOMPREQUEST.fields_by_name['level'].containing_oneof = _DECOMPREQUEST.oneofs_by_name['_level']
_DECOMPREQUEST.oneofs_by_name['_isDistributed'].fields.append(
  _DECOMPREQUEST.fields_by_name['isDistributed'])
_DECOMPREQUEST.fields_by_name['isDistributed'].containing_oneof = _DECOMPREQUEST.oneofs_by_name['_isDistributed']
_HYPERPARAMETERS.oneofs_by_name['_DecompositionName'].fields.append(
  _HYPERPARAMETERS.fields_by_name['DecompositionName'])
_HYPERPARAMETERS.fields_by_name['DecompositionName'].containing_oneof = _HYPERPARAMETERS.oneofs_by_name['_DecompositionName']
_HYPERPARAMETERS.oneofs_by_name['_numMicroservices'].fields.append(
  _HYPERPARAMETERS.fields_by_name['numMicroservices'])
_HYPERPARAMETERS.fields_by_name['numMicroservices'].containing_oneof = _HYPERPARAMETERS.oneofs_by_name['_numMicroservices']
_HYPERPARAMETERS.oneofs_by_name['_numGenerations'].fields.append(
  _HYPERPARAMETERS.fields_by_name['numGenerations'])
_HYPERPARAMETERS.fields_by_name['numGenerations'].containing_oneof = _HYPERPARAMETERS.oneofs_by_name['_numGenerations']
_HYPERPARAMETERS.oneofs_by_name['_numPopulations'].fields.append(
  _HYPERPARAMETERS.fields_by_name['numPopulations'])
_HYPERPARAMETERS.fields_by_name['numPopulations'].containing_oneof = _HYPERPARAMETERS.oneofs_by_name['_numPopulations']
_HYPERPARAMETERS.oneofs_by_name['_mutationProb'].fields.append(
  _HYPERPARAMETERS.fields_by_name['mutationProb'])
_HYPERPARAMETERS.fields_by_name['mutationProb'].containing_oneof = _HYPERPARAMETERS.oneofs_by_name['_mutationProb']
_HYPERPARAMETERS.oneofs_by_name['_attributeProb'].fields.append(
  _HYPERPARAMETERS.fields_by_name['attributeProb'])
_HYPERPARAMETERS.fields_by_name['attributeProb'].containing_oneof = _HYPERPARAMETERS.oneofs_by_name['_attributeProb']
_HYPERPARAMETERS.oneofs_by_name['_crossoverProb'].fields.append(
  _HYPERPARAMETERS.fields_by_name['crossoverProb'])
_HYPERPARAMETERS.fields_by_name['crossoverProb'].containing_oneof = _HYPERPARAMETERS.oneofs_by_name['_crossoverProb']
_HYPERPARAMETERS.oneofs_by_name['_seed'].fields.append(
  _HYPERPARAMETERS.fields_by_name['seed'])
_HYPERPARAMETERS.fields_by_name['seed'].containing_oneof = _HYPERPARAMETERS.oneofs_by_name['_seed']
_DECOMPOSITION.fields_by_name['partitions'].message_type = _PARTITION
DESCRIPTOR.message_types_by_name['DecompRequest'] = _DECOMPREQUEST
DESCRIPTOR.message_types_by_name['HyperParameters'] = _HYPERPARAMETERS
DESCRIPTOR.message_types_by_name['Partition'] = _PARTITION
DESCRIPTOR.message_types_by_name['Decomposition'] = _DECOMPOSITION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DecompRequest = _reflection.GeneratedProtocolMessageType('DecompRequest', (_message.Message,), {
  'DESCRIPTOR' : _DECOMPREQUEST,
  '__module__' : 'msextractor.v2.msextractor_pb2'
  # @@protoc_insertion_point(class_scope:msextractor.DecompRequest)
  })
_sym_db.RegisterMessage(DecompRequest)

HyperParameters = _reflection.GeneratedProtocolMessageType('HyperParameters', (_message.Message,), {
  'DESCRIPTOR' : _HYPERPARAMETERS,
  '__module__' : 'msextractor.v2.msextractor_pb2'
  # @@protoc_insertion_point(class_scope:msextractor.HyperParameters)
  })
_sym_db.RegisterMessage(HyperParameters)

Partition = _reflection.GeneratedProtocolMessageType('Partition', (_message.Message,), {
  'DESCRIPTOR' : _PARTITION,
  '__module__' : 'msextractor.v2.msextractor_pb2'
  # @@protoc_insertion_point(class_scope:msextractor.Partition)
  })
_sym_db.RegisterMessage(Partition)

Decomposition = _reflection.GeneratedProtocolMessageType('Decomposition', (_message.Message,), {
  'DESCRIPTOR' : _DECOMPOSITION,
  '__module__' : 'msextractor.v2.msextractor_pb2'
  # @@protoc_insertion_point(class_scope:msextractor.Decomposition)
  })
_sym_db.RegisterMessage(Decomposition)


DESCRIPTOR._options = None

_MSEXTRACTOR = _descriptor.ServiceDescriptor(
  name='MSExtractor',
  full_name='msextractor.MSExtractor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=812,
  serialized_end=903,
  methods=[
  _descriptor.MethodDescriptor(
    name='getDecomposition',
    full_name='msextractor.MSExtractor.getDecomposition',
    index=0,
    containing_service=None,
    input_type=_DECOMPREQUEST,
    output_type=_DECOMPOSITION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MSEXTRACTOR)

DESCRIPTOR.services_by_name['MSExtractor'] = _MSEXTRACTOR

# @@protoc_insertion_point(module_scope)
