# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msextractor/v2/msextractor.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n msextractor/v2/msextractor.proto\x12\x0bmsextractor\"\xcd\x01\n\rDecompRequest\x12\x0f\n\x07\x61ppName\x18\x01 \x01(\t\x12\x0f\n\x07\x61ppData\x18\x02 \x01(\t\x12:\n\x0fhyperParameters\x18\x03 \x01(\x0b\x32\x1c.msextractor.HyperParametersH\x00\x88\x01\x01\x12\x12\n\x05level\x18\x04 \x01(\tH\x01\x88\x01\x01\x12\x1a\n\risDistributed\x18\x05 \x01(\x08H\x02\x88\x01\x01\x42\x12\n\x10_hyperParametersB\x08\n\x06_levelB\x10\n\x0e_isDistributed\"\xff\x02\n\x0fHyperParameters\x12\x1e\n\x11\x44\x65\x63ompositionName\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x1d\n\x10numMicroservices\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x1b\n\x0enumGenerations\x18\x03 \x01(\x03H\x02\x88\x01\x01\x12\x1b\n\x0enumPopulations\x18\x04 \x01(\x03H\x03\x88\x01\x01\x12\x19\n\x0cmutationProb\x18\x05 \x01(\x02H\x04\x88\x01\x01\x12\x1a\n\rattributeProb\x18\x06 \x01(\x02H\x05\x88\x01\x01\x12\x1a\n\rcrossoverProb\x18\x07 \x01(\x02H\x06\x88\x01\x01\x12\x11\n\x04seed\x18\x08 \x01(\x03H\x07\x88\x01\x01\x42\x14\n\x12_DecompositionNameB\x13\n\x11_numMicroservicesB\x11\n\x0f_numGenerationsB\x11\n\x0f_numPopulationsB\x0f\n\r_mutationProbB\x10\n\x0e_attributeProbB\x10\n\x0e_crossoverProbB\x07\n\x05_seed\"*\n\tPartition\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63lasses\x18\x02 \x03(\t\"{\n\rDecomposition\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61ppName\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\r\n\x05level\x18\x04 \x01(\t\x12*\n\npartitions\x18\x05 \x03(\x0b\x32\x16.msextractor.Partition2[\n\x0bMSExtractor\x12L\n\x10getDecomposition\x12\x1a.msextractor.DecompRequest\x1a\x1a.msextractor.Decomposition\"\x00\x42\x32\n\x16\x63om.decomp.msextractorB\x10MSExtractorProtoP\x01\xa2\x02\x03MSEb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msextractor.v2.msextractor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.decomp.msextractorB\020MSExtractorProtoP\001\242\002\003MSE'
  _globals['_DECOMPREQUEST']._serialized_start=50
  _globals['_DECOMPREQUEST']._serialized_end=255
  _globals['_HYPERPARAMETERS']._serialized_start=258
  _globals['_HYPERPARAMETERS']._serialized_end=641
  _globals['_PARTITION']._serialized_start=643
  _globals['_PARTITION']._serialized_end=685
  _globals['_DECOMPOSITION']._serialized_start=687
  _globals['_DECOMPOSITION']._serialized_end=810
  _globals['_MSEXTRACTOR']._serialized_start=812
  _globals['_MSEXTRACTOR']._serialized_end=903
# @@protoc_insertion_point(module_scope)
